name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup tracy lib
        run: |
          cp ./lib/tracy.lib ./lib/tracy/
          cp ./lib/tracy.so ./lib/tracy/
      - name: make release build
        run: make

      - name: run tests
        run: make test

  build_netbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          copyback: false
          run: |
            set -e -x
            cp ./lib/tracy.lib ./lib/tracy/
            cp ./lib/tracy.so ./lib/tracy/
            make
            make test


  build_freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          run: |
            set -e -x
            cp ./lib/tracy.lib ./lib/tracy/
            cp ./lib/tracy.so ./lib/tracy/
            make
            make test
