name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, freebsd-latest, netbsd-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup tracy lib
        run: cp ./lib/tracy.lib ./lib/tracy/
      - name: make release build
        run: make

      - name: run tests
        run: make test
